LABEL default
  kernel /boot/%LINUXIMAGE%
  fdt /boot/allwinner/sun50i-h616-walnutpi-1b.dtb
  append root=/dev/mmcblk0p1 rootwait console=ttyS0,115200 console=tty1 earlycon=uart8250,mmio32,0x05000000 rootfstype=ext4
